services:
  back:
    container_name: server
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /project-package
    volumes:
      - .:/project-package/
      - ./transactions_files:/transactions_files
      - ./mail_template:/mail_template
    restart: always
    environment:
      GOFLAGS: -buildvcs=false
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - ServerNet

  db:
      image: postgres
      container_name: db
      restart: always
      environment:
        POSTGRES_PASSWORD: user
        POSTGRES_USER: user
        POSTGRES_DB: Stori
      ports:
        - 5432:5432
      networks:
      - ServerNet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - ServerNet

  swagger-ui:
   image: swaggerapi/swagger-ui
   container_name: swagger_ui_container
   ports:
      - "8082:8080"
   networks:
      - ServerNet   
   volumes:
      - ./doc:/usr/share/nginx/html/doc
   environment:
      API_URL: doc/swagger.json

  test:
    container_name: test
    image: test:latest
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    restart: always
    depends_on:
      - db
    networks:
      - ServerNet      

networks:
  ServerNet:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24