services:
  back:
    container_name: server
    image: server:latest
    build: 
      context: .
      dockerfile: ./Dockerfile
    entrypoint: /server
    restart: always
    volumes:
      - ./transactions_files:/transactions_files
      - ./mail_template:/mail_template
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - ServerNet

  db:
      image: postgres
      container_name: db
      restart: always
      environment:
        POSTGRES_PASSWORD: user
        POSTGRES_USER: user
        POSTGRES_DB: Stori
      ports:
        - 5432:5432
      networks:
      - ServerNet
networks:
  ServerNet:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24